[build]
  command = "npm run build"
  publish = "build/client"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/build/*"
  to = "/build/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173