import { useState, useEffect } from 'react';
import { redirect, Link } from 'react-router';
import { requireAuth } from '../lib/session';
import { Select, PageLayout, Card, CardContent, Button, Input } from '../components/ui';
import { ArrowLeft } from 'lucide-react';
import { prisma } from '../lib/db';
import { getAvailableYears } from '../lib/season.server';
// Types will be generated by React Router
type RouteParams = { photoId: string };
type LoaderArgs = { request: Request; params: RouteParams };
type ActionArgs = { request: Request; params: RouteParams };
type ComponentProps = { loaderData: any; actionData?: any };

export function meta({ params }: { params: RouteParams }) {
  return [
    { title: "Edit Photo - Scaletta Golf Trip" },
    { name: "description", content: "Edit photo details and category" },
  ];
}

export async function loader({ request, params }: LoaderArgs) {
  try {
    const user = await requireAuth(request);
    
    if (!user.isAdmin) {
      throw new Response("Unauthorized", { status: 403 });
    }

    const { photoId } = params;

    // Get the photo
    const photo = await prisma.photo.findUnique({
      where: { id: photoId },
      include: {
        user: {
          select: {
            name: true,
            email: true,
          },
        },
      },
    });

    if (!photo) {
      throw new Response("Photo not found", { status: 404 });
    }

    // Get all unique categories for the dropdown
    const allPhotos = await prisma.photo.findMany({
      select: { category: true },
    });
    const categories = [...new Set(allPhotos.map(photo => photo.category).filter(Boolean))];

    // Every season the trip has data for, not just years already on a photo.
    // The upload form can get away with the latter because it defaults to the
    // year you are filtering by, but this form exists precisely to sort photos
    // that have no year yet -- and on a gallery where none do, a list built from
    // photo years would offer nothing but the current season.
    const availableYears = await getAvailableYears();

    return { user, photo, categories, availableYears };
  } catch (response) {
    throw response;
  }
}

export async function action({ request, params }: ActionArgs) {
  const user = await requireAuth(request);
  
  if (!user.isAdmin) {
    throw new Response("Unauthorized", { status: 403 });
  }

  const { photoId } = params;
  const formData = await request.formData();
  const action = formData.get('_action') as string;

  if (action === 'edit-photo') {
    const caption = formData.get('caption') as string || undefined;
    let category = formData.get('category') as string;
    
    // If category is "custom", use the custom category input
    if (category === 'custom') {
      category = formData.get('customCategory') as string || '';
    }
    
    // Convert empty string to null to properly unset category
    const categoryValue = category && category.trim() !== '' ? category : null;

    // Same parse as the upload form: an empty or unparseable value means
    // "unsorted", which is a legitimate state rather than an error.
    const rawYear = formData.get('year') as string | null;
    const parsedYear = rawYear ? Number.parseInt(rawYear, 10) : NaN;
    const yearValue = Number.isInteger(parsedYear) ? parsedYear : null;

    try {
      // Check if photo exists
      const existingPhoto = await prisma.photo.findUnique({
        where: { id: photoId },
      });

      if (!existingPhoto) {
        return { error: "Photo not found" };
      }

      // Update photo in database
      await prisma.photo.update({
        where: { id: photoId },
        data: {
          caption,
          category: categoryValue,
          year: yearValue,
        },
      });
      
      return { success: true, message: 'Photo updated successfully' };
    } catch (error) {
      console.error('Photo edit error:', error);
      return { error: "Failed to update photo" };
    }
  }

  return { error: "Invalid action" };
}

export default function EditPhoto({ loaderData, actionData }: ComponentProps) {
  const { user, photo, categories, availableYears } = loaderData;
  const [showCustomCategory, setShowCustomCategory] = useState(false);

  // Reset form state when action succeeds
  useEffect(() => {
    if (actionData?.success) {
      setShowCustomCategory(false);
    }
  }, [actionData]);

  return (
    <PageLayout user={user} width="narrow">
        <div className="mb-8">
          {/* Back to Photos Link */}
          <Link 
            to="/gallery" 
            className="inline-flex items-center text-sm text-gray-500 hover:text-gray-700 mb-4"
          >
            <ArrowLeft size={16} className="mr-1" />
            Back to Photos
          </Link>
          
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            Edit Photo
          </h1>
          <p className="text-gray-600">
            Update the photo's caption, year and category
          </p>
        </div>

        <Card>
          <CardContent className="p-6">
            {/* Photo Preview */}
            <div className="mb-6 text-center">
              <img
                src={photo.url}
                alt={photo.caption || 'Photo preview'}
                className="max-w-md max-h-64 object-contain mx-auto rounded-lg border border-gray-300"
              />
              <p className="text-sm text-gray-500 mt-2">
                Uploaded by {photo.user.name}
              </p>
            </div>
            
            <form method="post" className="space-y-4">
              <input type="hidden" name="_action" value="edit-photo" />
              
              <div>
                <label htmlFor="caption" className="block text-sm font-medium text-gray-700 mb-1">
                  Caption
                </label>
                <Input 
                  id="caption"
                  name="caption" 
                  type="text" 
                  defaultValue={photo.caption || ''}
                  placeholder="Photo description"
                  className="w-full"
                />
              </div>
              
              <div>
                <label htmlFor="year" className="block text-sm font-medium text-gray-700 mb-1">
                  Year
                </label>
                <Select
                  id="year"
                  name="year"
                  defaultValue={photo.year != null ? String(photo.year) : ''}
                >
                  <option value="">Unsorted</option>
                  {availableYears.map((year: number) => (
                    <option key={year} value={year}>{year}</option>
                  ))}
                </Select>
                <p className="mt-1 text-sm text-gray-500">
                  Which trip this photo is from. Unsorted photos are hidden from the
                  year filter until assigned.
                </p>
              </div>

              <div>
                <label htmlFor="category" className="block text-sm font-medium text-gray-700 mb-1">
                  Category
                </label>
                <Select 
                  id="category"
                  name="category" 
                  defaultValue={photo.category || ''}
                  
                  onChange={(e) => setShowCustomCategory(e.target.value === 'custom')}
                >
                  <option value="">No category</option>
                  {categories.map((category: string) => (
                    <option key={category} value={category || ''}>{category}</option>
                  ))}
                  <option value="custom">+ Add new category</option>
                </Select>
              </div>

              {showCustomCategory && (
                <div>
                  <label htmlFor="customCategory" className="block text-sm font-medium text-gray-700 mb-1">
                    New Category Name
                  </label>
                  <Input 
                    id="customCategory"
                    name="customCategory" 
                    type="text" 
                    placeholder="Enter new category name"
                    className="w-full"
                    required
                  />
                </div>
              )}

              {actionData?.error && (
                <div className="text-red-600 text-sm bg-red-50 border border-red-200 rounded-md p-3">
                  {actionData.error}
                </div>
              )}

              {actionData?.success && (
                <div className="text-brand-600 text-sm bg-brand-50 border border-brand-200 rounded-md p-3">
                  {actionData.message}
                </div>
              )}

              <div className="pt-4">
                <Button type="submit">
                  Update Photo
                </Button>
              </div>
            </form>
          </CardContent>
        </Card>
    </PageLayout>
  );
}